[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_url = "https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"

[profile.dotenv]
path = ".env"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
sepolia_optimism = "https://sepolia.optimism.io"
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"
bsc_mainnet = "https://binance.llamarpc.com"
bsc_testnet = "https://bsc-testnet.publicnode.com"




[profile.dependencies]
OpenZeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.2" }

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
